fix: Update the S3Storage to work with both node version 8.x and 10.x
serverless/multicloud pull request #34
Opened 2019-10-30 17:12 UTC by etienne95

We modified the S3Storage file in order to read the readable object length both in node version 8.x and 10.x. We did that because when deployed an AWS handler that uploads a file in a bucket, the readable object in the 8.x node version doesn't have the readableLength property.

## What did you implement:

We updated the S3Storage to work with both node version 8.x and 10.x.

## How did you implement it:

We modified the S3Storage file in order to read the readable object length both in node version 8.x and 10.x. We did that because when deployed an AWS handler that uploads a file in a bucket, the readable object in the 8.x node version doesn't have the readableLength property.

## How can we verify it:

_Unit tests_

![image](https://user-images.githubusercontent.com/11664783/67881335-15cfab00-fb1f-11e9-817b-7d8be9e254d8.png)

## Todos:

_**Note: Run `npm run test-ci` to run all validation checks on proposed changes**_

- [X] Write tests and confirm existing functionality is not broken.
       **Validate via `npm test`**
- [X] Write documentation
- [X] Ensure there are no lint errors.
       **Validate via `npm run lint-updated`**
       _Note: Some reported issues can be automatically fixed by running `npm run lint:fix`_
- [X] Ensure introduced changes match Prettier formatting.
       **Validate via `npm run prettier-check-updated`**
       _Note: All reported issues can be automatically fixed by running `npm run prettify-updated`_
- [X] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [X] Enable "Allow edits from maintainers" for this PR
- [X] Update the messages below

**_Is this ready for review?:_** YES
**_Is it a breaking change?:_** NO

2019-10-30 20:33 UTC, lgaspari commented on aws/src/services/S3Storage.ts
> +      ContentLength: streamBody.readableLength || (streamBody as any)._readableState.length
I don't like the idea of accessing private properties we may investigate further about this

2019-11-14 19:00 UTC, wbreza requested changes
Let's see what other solutions we can find vs accessing the private members.

2019-11-14 19:00 UTC, wbreza commented on aws/src/services/S3Storage.test.ts
> +      ContentLength: readableBody.readableLength || (readableBody as any)._readableState.length
Let's see what other solutions we can find.  The `readableState` is not exposed as a public member somewhere?

2019-11-19 14:18 UTC, etienne95 commented
We will close this PR because we will use the node.js 10.x version.

2019-11-19 14:18 UTC, closed without merging